services:
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/prometheus/data:/prometheus
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    user: "nobody"
