services:
  tunarr:
    image: ghcr.io/chrisbenincasa/tunarr:0.22.0
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/tunarr/config:/config
    environment:
      - TZ=${TZ:-Europe/Berlin}
