services:
  gitlab:
    image: gitlab/gitlab-ce:18.2.1-ce.0
    restart: unless-stopped
    hostname: localhost
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/gitlab/config:/etc/gitlab
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/gitlab/logs:/var/log/gitlab
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "${GITLAB_OMNIBUS_CONFIG:-external_url 'http://localhost'; gitlab_rails['gitlab_shell_ssh_port'] = 22;}"
    shm_size: '256m'
