d /var/lib/upcode-harbor 0700 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/app-store 0750 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/compose 0750 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/app-data 0750 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/customization 0750 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/ssh_keys 0700 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/authorized_keys 0700 upcode-harbor upcode-harbor -
d /var/lib/upcode-harbor/updates 0750 root upcode-harbor -
d /var/lib/upcode-harbor/update-state 0750 root upcode-harbor -
d /var/lib/upcode-harbor-web 0700 upcode-harbor-web upcode-harbor-web -
d /var/log/upcode-harbor 0750 upcode-harbor upcode-harbor -
d /run/upcode-harbor 0750 upcode-harbor upcode-harbor -
d /var/backups/upcode-harbor 0700 root root -
d /opt/upcode-harbor/releases 0755 root root -
