services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/nginx-proxy-manager/data:/data
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
