services:
  typo3-db:
    image: mariadb:11.4.8
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/typo3/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-typo3}
      - MYSQL_USER=${MYSQL_USER:-typo3}
      - MYSQL_PASSWORD=${TYPO3_DB_PASSWORD:?TYPO3_DB_PASSWORD is required}
    command: '--default-authentication-plugin=mysql_native_password'

  typo3:
    image: typo3/typo3:13.4.14
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/typo3/html:/var/www/html
    environment:
      - TYPO3_DB_HOST=${TYPO3_DB_HOST:-typo3-db}
      - TYPO3_DB_DRIVER=mysqli
      - TYPO3_DB_USERNAME=typo3
      - TYPO3_DB_PASSWORD=${TYPO3_DB_PASSWORD:?TYPO3_DB_PASSWORD is required}
      - TYPO3_DB_NAME=${TYPO3_DB_NAME:-typo3}
      - TYPO3_INSTALL_TOOL_PASSWORD=${TYPO3_INSTALL_TOOL_PASSWORD:?TYPO3_INSTALL_TOOL_PASSWORD is required}
      - TYPO3_CONTEXT=Development
    depends_on:
      - typo3-db
