version: '3.8'

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /opt/upservx/data/emby/config:/config
      - /mnt/media:/media
    ports:
      - "8096:8096"
      - "8920:8920"
