services:
  mongodb:
    image: mongo:8.0.13
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/mongodb/data:/data/db
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/mongodb/config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?MONGO_INITDB_ROOT_PASSWORD is required}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-mydb}
