services:
  traefik:
    image: traefik:3.5.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/traefik/config:/etc/traefik
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/traefik/acme:/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TRAEFIK_API_INSECURE=${TRAEFIK_API_INSECURE:-true}
      - TRAEFIK_API_DASHBOARD=${TRAEFIK_API_DASHBOARD:-true}
      - TRAEFIK_PROVIDERS_DOCKER=${TRAEFIK_PROVIDERS_DOCKER:-true}
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=${TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT:-false}
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=${TRAEFIK_ENTRYPOINTS_WEB_ADDRESS:-:80}
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=${TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS:-:443}
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-INFO}
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: false
