services:
  jenkins:
    image: jenkins/jenkins:2.516.1-lts-jdk21
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS:---prefix=/jenkins}
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
