services:
  loki:
    image: grafana/loki:3.5.3
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/loki/data:/loki
      - ${APP_DATA_DIR:?APP_DATA_DIR is required}/loki/config:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    user: "10001"
